**例**：   
处理前： 
|特征1|特征2|特征3|特征4|
|:-:|:-:|:-:|:-:|
|90|2|10|40|
|60|4|15|45|
|75|3|13|46|

处理后：
|特征1|特征2|特征3|特征4|
|:-:|:-:|:-:|:-:|
|1.|0.|0.|0.|
|0.|1.|1.|0.83|
|0.5|0.5|0.6|1.| 

## 什么是特征预处理
通过**一些转换函数**将特征数据**转换成更加适合算法模型**的特征数据过程

* 数值型数据的无量纲化：
   * 归一化
   * 标准化

* 特征预处理API
   `sklearn.preprocessing`

## 为什么要进行 归一化/标准化
   **无量纲化**，使不同规格的数据转化成相同的规格

# 归一化
1. 定义
   通过对原始数据进行变换把数据映射到（默认为[0,1]）之间

2. 公式  
$X' = \frac{X - min}{max - min}$  
$X'' = X' \times (mx - mi) + mi$  
   * $max$ 为一列的最大值
   * $min$ 为一列的最小值
   * $mx$ 为指定区间最大值，默认为1
   * $mi$ 为指定区间最小值，默认为0

3. 缺点
**如果异常值发生在最大值和最小值时，可能对结果影响变大**

**例**：   
|特征1|特征2|特征3|特征4|
|:-:|:-:|:-:|:-:|
|90|2|10|40|
|60|4|15|45|
|75|3|13|46|

* 第一列：
   * 第一行：
      * $X' = \frac{90 - 60}{90-60} = 1$
      * $X'' = 1 \times (1 - 0) + 0 = 1$

* 第四列：
   * 第二行：
      * $X' = \frac{45 - 40}{46-40} = 0.83$
      * $X'' = 0.83 \times (1 - 0) + 0 = 0.83$

* `sklearn.preprocessing.MinMaxScaler(feature_range=(0, 1)...)`
   * `MinMaxScalar.fit_transform(X)`
      * X: numpy array 格式的数据[n_samples, n_features]
   * 返回值：转换后的形状相同的 array 

In [7]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

def minmax_demo():
    """
    归一化
    :return:
    """
    # 1. 获取数据
    data = pd.read_csv("12data.txt")
    data = data.iloc[:, :3] # [所有行， 前三列]
    # 2. 实例化转换器类
    transfer = MinMaxScaler()
    # 3. 调用fit_transform
    data_new = transfer.fit_transform(data)
    print(data_new)
    return None

if __name__ == "__main__":
    minmax_demo()

[[0.49233319 0.54426209 0.52815847]
 [0.12421487 0.46756013 0.99207108]
 [0.28526663 0.09424258 0.43225877]
 [0.96885924 0.85933095 0.18987405]
 [0.45645725 0.10913954 0.        ]
 [0.93901369 0.66287745 0.57906532]
 [0.42308817 0.44646954 0.69520392]
 [0.86247093 0.56417122 0.3962735 ]
 [0.41661212 0.80219045 0.88520233]
 [0.62216063 0.24337272 0.44952327]
 [0.80367116 0.54811207 0.98922362]
 [0.         0.31866484 0.38298668]
 [0.6334415  0.30589736 0.31633732]
 [1.         1.         0.12697555]
 [0.53067421 0.12349765 0.03672049]
 [0.77705667 0.49130492 0.73127037]
 [0.89277607 0.9306925  0.08185833]
 [0.14066265 0.         0.71904095]
 [0.31919279 0.68816019 0.75426135]
 [0.01278498 0.23139637 0.44344432]
 [0.44759968 0.1955317  0.45081393]
 [0.23746919 0.34627542 0.32476692]
 [0.32328733 0.43097963 0.03403026]
 [0.19734551 0.18410714 1.        ]
 [0.43478685 0.81428811 0.33205534]
 [0.00239544 0.         0.98080369]
 [0.32029302 0.65156393 0.38464527]
 [0.01725555 0.08920761 0.32